version: '3'
services:
  spark-master:
    image: master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - /save:/save
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark_cluster
  spark-worker-1:
    image: worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - /save:/save
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark_cluster
  spark-worker-2:
    image: worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - /save:/save
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark_cluster
  spark-worker-3:
    image: worker
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - /save:/save
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark_cluster
  script-1:
    image: classifier
    container_name: classifier
    privileged: true
    depends_on:
      - spark-master
    volumes:
      - /save:/save
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - VOLUME_PATH_HOST=/save
      - SQLITE_VERSION=3.30.1
      - TABLE=Fires
      - PREDICTORS=<string of numeric variables comma separated>
      - TARGET=<multi class target var>
      - DATETIME_COL=<julian time column name>
      - METRIC=<evaluation metric>
    networks:
      - spark_cluster
    links:
      - spark-master
    ports:
      - "8084:8081"
networks:
  spark_cluster:
    driver: bridge
    external:
      name: spark_cluster